### PR TITLE
Up to net 4 0

### PR DESCRIPTION
**Pull request by AlexanderKarifanov**
Robert asked to update the repository.

### CODE REVIEW

**Comment by VSchuster** [comment]
This has been talked about in our meetings. We are saving the framework change for the next major release of landis-ii as it has a chance to break extensions (unlikely but don't want to take the risk without verifying there are no issues). If you need to, you can continue to use the version you built. I tested the .NET 4.0 upgrade on core-model, LSML, and base-fire. It seemed to work fine. If you need to run scenarios for the .NET 4.0, you can either create an installer (instructions are found `/model/README_CoreModel6.1.txt`) or continue to use the developer Debug method to run extensions on Landis-ii with .NET 4.0 upgrade.

Please do not include generated .sln files into pull requests. They are specific to each user and how they set up their workspace. Which is why we require the use of premake5 to generate them.

EDIT: as mentioned .csproj are ok.

**Comment by rmscheller** [comment]
.csproj files are OK to pull.  They are generic to the project, not user specific.

**Comment by rmscheller** [comment]
These cs project files are generated via premake.lua files, so no need to upload the individual *.csproject files and associated.  
Alex, why the change to Dataset.cs?
Thanks!!
Rob

**Comment by AlexanderKarifanov** [comment]
Hi, 
extensions.xml hosts at "../bin/extensions/extensions.xml" in my case.
Without my change Landis looked for this file at  "{executing assembly path/extensions.xml}" (executing assembly is Landis.Extensions.Dataset.dll  then executing assembly dirrectory is "../bin/6.2/"). We need go one level up and then go to the extensions folder (..\extensions)

Alex

**Pull request merged**
